using System.Collections.Generic;

namespace AcEvoFfbTuner.Help;

/// <summary>
/// The complete built-in Help guide content, in plain language for any user.
/// Articles are ordered logically: first run → each app page in sidebar order →
/// settings → troubleshooting. Every slider describes both what it does and the
/// "feel" it produces, so users can tune by hand and by feel.
/// </summary>
public static class HelpCatalog
{
    public static IReadOnlyList<HelpArticle> Articles { get; } = Build();

    private static HelpParagraph P(string text) => new(text);
    private static HelpBullets B(params string[] items) => new(items);
    private static HelpNote Note(string title, string text) => new(title, text);
    private static HelpSliderRow Hsl(string name, string range, string feel) => new(name, range, feel);
    private static HelpSection S(string heading, params HelpBlock[] blocks)
    {
        var s = new HelpSection { Heading = heading };
        s.Blocks.AddRange(blocks);
        return s;
    }

    private static HelpArticle A(string title, string subtitle, string[] keywords, params HelpSection[] sections)
    {
        var article = new HelpArticle
        {
            Title = title,
            Subtitle = subtitle,
            Keywords = keywords
        };
        article.Sections.AddRange(sections);

        var sb = new System.Text.StringBuilder();
        sb.Append(title).Append(' ').Append(subtitle).Append(' ');
        foreach (var k in keywords) sb.Append(k).Append(' ');
        foreach (var s in sections)
        {
            sb.Append(s.Heading).Append(' ');
            foreach (var b in s.Blocks)
            {
                switch (b)
                {
                    case HelpParagraph p: sb.Append(p.Text).Append(' '); break;
                    case HelpBullets bl:
                        foreach (var i in bl.Items) sb.Append(i).Append(' ');
                        break;
                    case HelpNote n: sb.Append(n.Title).Append(' ').Append(n.Text).Append(' '); break;
                    case HelpSliderRow sl:
                        sb.Append(sl.Name).Append(' ').Append(sl.Range).Append(' ').Append(sl.Feel).Append(' ');
                        break;
                }
            }
        }
        article.SearchText = sb.ToString().ToLowerInvariant();
        return article;
    }

    private static List<HelpArticle> Build()
    {
        var articles = new List<HelpArticle>
        {
            A("Welcome & Getting Started", "First run, setup wizard, and the ideas behind the app",
                new[] { "welcome", "first run", "setup", "wizard", "getting started", "start", "install", "begin" },
                S("What this app does",
                    P("AC Evo FFB Tuner replaces the force feedback your game produces with its own, far more detailed signal. It reads the real tyre physics from the game's shared memory (per-wheel grip, slip, load and torque) and turns them into forces for your wheel, vibration for your haptic pad, and pulses for your pedals."),
                    P("Because it builds the force signal itself, the app can make a car feel completely different: firmer at the centre, more alive over kerbs, clearer at the grip limit. Every one of those decisions is controlled by the sliders you will find in the FFB Tuning page, and every slider is explained in the FFB Tuning article.")),
                S("Supported games",
                    B("Assetto Corsa EVO — full per-wheel physics (the most detailed pipeline)",
                        "Assetto Corsa (AC 1) — full per-wheel physics",
                        "RaceRoom Racing Experience — column-force pipeline",
                        "Le Mans Ultimate — column-force pipeline",
                        "Assetto Corsa Competizione (ACC) — internal pipeline"),
                    P("Some pages show different sliders depending on the game that is currently selected. The app switches automatically when it detects a running game, or you can pick one from the Game pill in the top bar.")),
                S("First-time setup",
                    B("Connect your FFB wheel to the PC and select it from the Device pill in the top bar. See the Wheel Base Setup article for steps specific to your base (Moza, Fanatec, Logitech, Thrustmaster…).",
                        "Open your game's own FFB settings and set the FFB Gain slider to 0, then restart the game. The app replaces the game's FFB entirely — if both are active they fight over the wheel. The app reminds you of this with a banner until it is done.",
                        "Launch the Setup Wizard from the Home page. It walks you through choosing your wheel, setting steering lock and torque, and testing that forces feel right, then saves a starting profile.",
                        "Press START in the top bar, jump in the car, and drive. Adjust sliders on the FFB Tuning page while driving — changes apply instantly.",
                        "When a car or track feels good, save it as a profile (top bar Save button) so it can auto-load next time you drive that car."),
                    Note("Why the game's FFB must be off",
                        "The wheel can only usefully receive force from one source at a time. When both the game and this app send forces, they add together or fight, causing erratic feel, oscillation and clipping. Turn the game FFB to 0 and restart it — the app then has full control.")),
                S("The big ideas",
                    B("Profiles — every slider setting is stored in a named profile. Save one per car, per track, or per preference and switch instantly.",
                        "Per-car auto-load — profiles can be matched to a car model so the right one loads automatically when you drive that car.",
                        "Snapshots — pressing your assigned snapshot button (see Devices → Buttons) saves a moment of telemetry for analysis, which is how the app diagnoses problems.",
                        "Safety — the app has a Panic Stop button that zeroes all force instantly, plus safety clamps on crash forces by default."))
            ),

            A("Wheel Base Setup", "Getting your specific wheel base ready: driver software, base modes, torque and lock",
                new[] { "wheel base", "moza", "fanatec", "logitech", "thrustmaster", "simagic", "simucube", "cammus", "r5", "r9", "r12", "r16", "r21", "csl dd", "dd pro", "gt dd", "dd1", "dd2", "g29", "g920", "g923", "g pro", "t300", "t150", "t248", "t818", "alpha", "alpha ultimate", "simucube 2", "driver", "pithouse", "pit house", "g hub", "firmware", "torque", "steering lock", "mode", "compatibility mode", "auto center" },
                S("The universal recipe (every wheel base)",
                    P("Every wheel base follows the same five steps. The sections below only add base-specific details on top of these:"),
                    B("Connect the base via USB (and mains power if it needs it) and install its driver software once, so the base runs at its latest firmware.",
                        "Close the driver software (Moza Pit House, Logitech G HUB, the Fanatec driver, SimPro Manager…) before running the app. The app needs exclusive access to the wheel — the 'CONFLICTING FFB APPS DETECTED' banner appears if something else holds it.",
                        "Open your game's FFB settings, set the FFB Gain slider to 0 and restart the game — the app replaces the game's force entirely.",
                        "Select your wheel in the Device pill in the top bar, then launch the Setup Wizard from the Home page. It sets your steering lock, torque and force direction and saves a starting profile.",
                        "Check that the app's Steering Lock slider (FFB Tuning → Master Output) matches the lock set in your base's own software, then drive and adjust."),
                    Note("Max Torque is display-only",
                        "The Max Torque (Nm) slider only tells the app how strong your base is, so force readouts show real Nm — it does not change the force itself. The Setup Wizard sets it for you: 5.5 = Moza R5, 9 = Moza R9, 15 = Fanatec ClubSport DD / Simagic Alpha, 25 = Simucube 2 Pro.")),
                S("Moza (R5, R9, R12, R16, R21)",
                    P("Moza bases work well with the app over DirectInput. Moza Pit House is used for firmware and base settings, then must be closed while the app runs."),
                    B("In Pit House, set the base's FFB working mode to MOZA mode (raw force), not a per-game preset. Game presets layer the base's own canned forces on top of the app's signal, which makes the wheel feel doubled and mushy.",
                        "Set the steering angle in Pit House to match the app's Steering Lock slider (900° is a good default).",
                        "Pit House locks the wheel's serial port, which the app uses for LED control — close Pit House before starting the app if your LED strip does not light up.",
                        "Rated torque: R5 = 5.5 Nm, R9 = 9 Nm, R12 = 12 Nm, R16 = 16 Nm, R21 = 21 Nm."),
                    Note("Strong bases feel springy?",
                        "On R9 and above, if the wheel springs back or oscillates after a slide, lower Active Decay and Return Decay in FFB Tuning → Steering Friction (try 0.5–0.8 and 0.1–0.4) and raise Velocity Deadzone in Signal Processing.")),
                S("Fanatec (CSL DD, DD Pro, GT DD, DD+, DD1, DD2, ClubSport)",
                    P("The app uses the Fanatec SDK automatically when the Fanatec driver is installed (higher-quality output and LED support) and falls back to standard DirectInput otherwise — either path works."),
                    B("Put the base in PC mode (blue LED), not Compatibility Mode (yellow). PC mode is required for the SDK path and is the right mode for modern PC titles.",
                        "Set SEN (steering angle) on the wheel so the base's rotation matches the app's Steering Lock slider.",
                        "In the base tuning menu keep FF (force feedback strength) at 100 — the app controls the force — and disable canned effects such as centering springs.",
                        "Rated torque: CSL DD / DD Pro = 5 Nm, or 8 Nm with the Boost Kit; DD+ = 15 Nm; DD1 = 20 Nm; DD2 = 25 Nm; ClubSport DD ≈ 15 Nm.")),
                S("Logitech (G29, G920, G923, G Pro, RS50)",
                    P("G29/G920 are gear-driven: they feel slightly notchy and peak around 2 Nm, which is normal. The app automatically keeps Logitech effects refreshed so the force does not fade out over time."),
                    B("Close Logitech G HUB while the app runs — it can hold exclusive access to the wheel and cause connection failures.",
                        "G29/G920 rotate a fixed 900°; leave the app's Steering Lock at 900.",
                        "If your base supports adjustable rotation (G923, G Pro), set its steering angle in G HUB to match the app's Steering Lock.",
                        "Rated torque: G29/G920 ≈ 2.1–2.5 Nm, G923 ≈ 2.2–2.5 Nm, G Pro / RS50 = 11 Nm.")),
                S("Thrustmaster (T300, T150, T248, TX, T818)",
                    P("Belt-driven T300/TX bases have an internal auto-centering spring in their on-wheel menu that can fight the app's force."),
                    B("In the base's on-wheel menu set Auto-Center to Constant (or its weakest equivalent) — Spring mode adds a competing centering force.",
                        "On wheels without an auto-center menu (T150), just set the game FFB to 0 as usual.",
                        "Rated torque: T300/TX ≈ 4.5 Nm (peak), T818 = 10 Nm.")),
                S("Simagic, Simucube, Cammus and other direct-drive bases",
                    P("Any base that shows up in the Device pill works via DirectInput. The universal recipe applies; only the driver software name changes."),
                    B("Close the vendor's tuning software while the app runs — SimPro Manager (Simagic), TrueDrive (Simucube), Cammus Assistant — any of them can hold the wheel.",
                        "These bases are strong: keep the Crash Safety Clamp enabled and start with a modest Output Gain, then raise it as you get used to the force.",
                        "If the wheel feels too 'alive' on a strong base, lower Max Slew Rate and add a little Speed Damping.",
                        "Rated torque: Simagic Alpha = 15 Nm, Alpha Ultimate = 23 Nm, Simucube 2 Pro = 25 Nm, Cammus C12 = 12 Nm.")),
                S("Rated torque quick reference",
                    P("The app's built-in default profiles are keyed to these torque figures — the Setup Wizard and wheelbase auto-detection pick the closest one automatically."),
                    B("Logitech G27 — 2.5 Nm (gear driven)",
                        "Logitech G29 / G920 — 2.1 Nm (gear driven)",
                        "Thrustmaster T300 / TX — 4.5 Nm (belt driven)",
                        "Fanatec CSL DD — 5 Nm, or 8 Nm with the Boost Kit",
                        "Moza R5 — 5.5 Nm",
                        "Moza R9 — 9 Nm",
                        "Fanatec ClubSport DD / Simagic Alpha — 15 Nm",
                        "Simagic Alpha Ultimate — 23 Nm",
                        "Simucube 2 Pro — 25 Nm"))
            ),

            A("The Main Window", "Top bar controls, status bar, and warning banners",
                new[] { "main window", "header", "top bar", "start", "stop", "panic", "device", "game", "profile pill", "status bar", "record", "send to dev" },
                S("The top bar",
                    P("Everything important lives in the top bar so it is reachable from any page."),
                    B("Device pill — shows the connected FFB wheel. Click to choose another device.",
                        "Game pill — shows the detected game. Click to cycle or switch games manually.",
                        "Profile pill — shows the active profile. Click to switch profile, lock it (so it never auto-switches), or save a copy with Save As.",
                        "Save — saves the current slider settings into the active profile.",
                        "Pop Out — opens the compact tuner window: a small, always-on-top window with the most-used tuning sliders.",
                        "REC — records the app window to video (stored in your recordings folder).",
                        "Chat — check replies from the developer to diagnostic packs you have sent.",
                        "Send to Dev — packages profiles, logs, snapshots and track maps into a diagnostic ZIP and sends it to the developer. Extremely useful when reporting a problem.",
                        "PANIC — instantly zeroes all FFB output. The wheel goes dead until you press START again. Use it any time the wheel does something dangerous.",
                        "START / STOP — starts and stops the whole telemetry and force pipeline. The app must be running (and the game in focus) to feel anything."),
                    Note("Pro tip",
                        "You can also assign a physical wheel button as a panic stop — see Devices → Buttons. A hardware panic button on a separate device (like a button box) is the safest setup.")),
                S("The status bar (bottom)",
                    P("The bottom strip shows the system log (the most recent app events), the game connection status, the telemetry packet rate (pkt/s), and the current force output in Nm. A red dot appears when the app is actively recording.")),
                S("Warning banners",
                    P("The app may show two important banners at the top of the content area:"),
                    B("IN-GAME FFB IS STILL ACTIVE — the game's own FFB is fighting the app. Set the game's FFB gain to 0 and restart it.",
                        "CONFLICTING FFB APPS DETECTED — another app is also sending forces to the wheel. Close it; two FFB sources cannot coexist."),
                    P("Both banners can be dismissed once resolved, and they reappear every time the situation is detected again."))
            ),

            A("FFB Tuning (Wheel)", "Every force effect and slider for the steering wheel, and what each one feels like",
                new[] { "ffb tuning", "wheel", "slider", "mz", "fx", "fy", "torque", "gain", "force", "center", "suppression", "damping", "slip", "vibration", "kerb", "lfe", "output gain", "sensitivity", "steering lock", "wet" },
                S("How to use this page",
                    P("This is the heart of the app: every force that reaches your wheel, in one long list of section cards. Sections expand and collapse. The search box at the top filters the sections by name (try 'kerb' or 'wet'). A summary bar shows the current car, wheel, profile, peak force, and mix mode."),
                    P("Important: which sections appear depends on the selected game. Per-wheel games (AC EVO, Assetto Corsa) show the tyre-force sections; column-force games (RaceRoom, Le Mans Ultimate) show the Core Force section instead; ACC shows a slimmed-down set. This guide describes everything — you will only see the sections your game supports."),
                    P("Every slider applies instantly while driving, and most have a small reset button (↺) to return to the profile default. Tune with the car on track, one slider at a time."),
                    Note("Golden rule", "Change one thing at a time and drive a full corner before judging. Most 'bad' FFB is two effects fighting each other — usually too much of everything.")),
                S("Master Output (right-hand sidebar)",
                    P("The pinned right sidebar holds the master controls that shape the final signal after every effect is mixed."),
                    Hsl("Output Gain", "0 – 20", "The final master volume of everything. Higher = stronger overall force. This is the 'is it too weak or too strong?' control — adjust it first, then balance the effect sliders."),
                    Hsl("Max Force Limit", "0.1 – 1.0", "A soft limiter: forces above this level are gently rounded off instead of slamming. Lower = safer, softer peaks. If the wheel frequently feels like it hits a hard wall in fast corners, lower this slightly."),
                    Hsl("Sensitivity", "1 – 1000 (log)", "The first gain stage, applied to raw game forces. It is inverted: higher = weaker forces, lower = stronger. Used for fine headroom control before the effect mix."),
                    Hsl("Max Slew Rate", "0.03 – 0.50", "The fastest a force is allowed to change per frame. Lower = smoother, more 'glued' feel but can feel laggy; higher = snappier and punchier, but can feel jittery. Raise it if the wheel feels mushy; lower it if forces feel nervous."),
                    B("Sign Correction — on by default: makes self-centering forces point the correct direction near centre. Leave it on unless the wheel feels wrong around centre.",
                        "Invert Force — flips the direction of ALL forces. If the wheel pushes the wrong way entirely (feels reversed), toggle this.",
                        "Invert Lateral Force — flips the lateral (cornering) force direction. If the car seems to pull to one side under braking, toggle this."),
                    Hsl("Steering Lock", "180° – 3600°", "Your wheel's total rotation, end to end. Must roughly match what the wheel is set to, otherwise angles and centre behaviour misalign. 900° is the common default."),
                    Hsl("Max Torque (Nm)", "1 – 25 Nm", "Your wheelbase's rated peak torque — used only to display force in Nm (5.5 = Moza R5, 9 = R9, 15 = R15). Does not change the force itself."),
                    B("Mix Mode — Replace: the app's force replaces the game FFB channel and the game's own signal is added as an extra effect. Overlay: the app force is layered over the game's signal. Replace is the normal choice.",
                        "Response Curve — presets that reshape the final force vs input curve: Linear, Soft Center (less force exactly at centre), Progressive (more force the harder you turn), Dead Zone (a quiet zone at centre).")),
                S("Tyre Forces",
                    P("The three raw tyre forces from the front axle, scaled to feel right. These are the backbone of the wheel feel in per-wheel games."),
                    Hsl("Mz (Self-Align)", "-10 to +10", "The main steering feel: the force that pulls the wheel back to centre as the tyres self-align. Higher = firmer, more connected centre and stronger return; too high = heavy and washy; too low = vague, floaty centre."),
                    Hsl("Fx (Longitudinal)", "-10 to +10", "Braking and acceleration force through the wheel. Higher = more 'nose dive' under braking and 'squat' under throttle. Adds a lot of life to braking zones."),
                    Hsl("Fy (Lateral)", "-10 to +10", "Cornering load feel — the weight you feel in your hands while turning. Higher = heavier steering effort in corners. Suppressed near centre by Center Blend so it does not buzz on straights."),
                    Hsl("Mz Scale (Aligning)", "1 – 500 (log)", "Divides raw Mz values to normalise them. Lower = stronger Mz feel. If steering feels weak even with Mz gain maxed, lower this."),
                    Hsl("Fx Scale (Longitudinal)", "100 – 20000 (log)", "Divides raw Fx values. Lower = stronger braking/acceleration feel."),
                    Hsl("Fy Scale (Lateral)", "100 – 20000 (log)", "Divides raw Fy values. Lower = stronger cornering feel."),
                    Hsl("Mz Rear / Fx Rear / Fy Rear", "-10 to +10 each", "The same three forces from the rear axle. Usually left off — they add subtle rear-end feel but can add noise and mask the front signals. Useful for feeling the rear of the car rotate."),
                    Hsl("Game FFB Output", "-10 to +10", "The game's own built-in FFB signal. In Replace mode it is added on top as an effect; in Overlay mode it is the base signal. Higher = more of the game's original feel bleeds through."),
                    Hsl("Wheel Load Weighting", "0 – 1", "How much real tyre load influences the mixing. 0 = simple average of the four wheels; 1 = force follows the loaded tyres, which feels more natural mid-corner."),
                    Hsl("Force Gain (ACC)", "0 – 10", "ACC only: a global multiplier applied to the final output. Higher = stronger overall force (default 2.5).")),
                S("Tyre Slip",
                    P("Extra force when the tyres are slipping — wheelspin, locked wheels, and slides."),
                    Hsl("Slip Ratio Gain", "0 – 5", "Extra force during wheelspin (driven wheels) or wheel lock-up (braking). Higher = the wheel pulses and stutters more obviously when you spin up the rears. Needs the threshold set correctly."),
                    Hsl("Slip Angle Gain", "0 – 5", "Extra force when the tyres slide sideways — i.e. oversteer and drifting. Higher = the wheel fights you more as the car steps out, giving early warning before the slide becomes a spin."),
                    Hsl("Slip Angle Shape Gain", "0 – 5", "Shapes how the slip response ramps up. 0 = linear; higher = a progressive build that gets stronger the deeper the slide — a 'loading up' feel just before and at the grip limit."),
                    Hsl("Slip Threshold", "0 – 1", "How much slip must exist before the slip effects wake up. Lower = more sensitive (effects trigger early); higher = only pronounced slips are felt. If you feel slip noise during normal cornering, raise it."),
                    B("Front Wheels Only — restrict slip effects to the front axle. On by default for stability; disable to feel rear slides too.")),
                S("Tyre at the Limit",
                    P("Textures that tell you the tyres are approaching their grip ceiling — per-wheel games only."),
                    Hsl("Front Tire Scrub", "0 – 1", "A high-frequency grain (30–50 Hz) as the front tyres near their limit, before the aligning torque drops. It feels like rubber tearing at the contact patch. 0 = off, 0.15 = subtle, 0.5 = strong. This is the 'the front is about to let go' whisper."),
                    Hsl("Rear Slip Warning", "0 – 1", "A low-frequency rumble (12–25 Hz) when the rear tyres lose grip, built from rear slip angle and yaw. Feels like a deep warning shake from the back of the car. 0.25 = default, 0.5 = strong.")),
                S("Tyre Flex",
                    P("The physical squirm and stretch of the tyre carcass under load transfer."),
                    Hsl("Carcass Flex Gain", "0 – 5", "Sidewall flex from rapid weight shifts — braking, corner entry, kerb strikes. Higher = more 'tyre squirm' detail in your hands, a soft elastic feel under load."),
                    Hsl("Contact Patch Gain", "0 – 5", "Feel for how the tyre's grip footprint changes with load and slip. Higher = more detailed, alive feel at the limit as the patch grows and shrinks."),
                    Hsl("Carcass Stiffness", "0.1 – 5", "Tuning of the flex model itself: lower = softer, more flexible tyres (more squirm feel); higher = stiffer sidewall (less). Default 1.0."),
                    Hsl("Flex Smoothing", "0 – 0.95", "Smoothing on the flex forces. Higher = smoother but laggier; lower = more responsive but noisier. Default 0.70."),
                    Hsl("Contact Patch Weight", "0 – 2", "How strongly lateral G-force drives contact-patch variation. Higher = more feel from direction changes and weight transfer.")),
                S("Steering Friction (stationary)",
                    P("Simulates stationary tyre scrub when the car is stopped — an elastic model with no centering bias and no oscillation. This is what makes the wheel feel 'planted' in the pits or at a standstill."),
                    Hsl("Master Gain", "0 – 2", "Overall intensity of stationary friction. 0 = disabled (wheel goes light when stopped), 1 = normal, 2 = extra heavy."),
                    Hsl("Engine Off Scale", "0 – 2", "Force multiplier with the engine off — like a dead car with no power steering: heavier, rubbery resistance."),
                    Hsl("Engine On Scale", "0 – 1", "Force multiplier with the engine running — power assist makes it lighter. Lower = lighter steering effort when idling."),
                    Hsl("Elastic Stretch", "0.001 – 0.05", "How far the tyre deforms elastically before it breaks free. Smaller = sharper breakaway, more 'clunk' when it lets go; larger = more rubbery, gradual feel. Default 0.01."),
                    Hsl("Spring Stiffness", "1 – 50", "How quickly the resistance builds in the elastic zone. Higher = stiffer initial resistance when you start turning at a standstill. Default 15."),
                    Hsl("Kinetic Friction", "0 – 1", "The sliding-friction level once the tyre has broken free. Higher = heavier continuous drag when scrubbing. Default 0.20."),
                    Hsl("Engine Off Damping", "0 – 0.5", "Viscous damping with the engine off — absorbs motor inertia so the wheel does not buzz. Default 0.15."),
                    Hsl("Engine On Damping", "0 – 0.2", "Viscous damping with the engine running — much lower, simulating power assist. Default 0.02."),
                    Hsl("Active Decay", "0.5 – 1", "How fast the elastic displacement fades while you are turning. Lower = faster decay = more stable on strong wheels. 0.92 default; try 0.5–0.8 on very strong wheelbases if it feels springy."),
                    Hsl("Return Decay", "0.1 – 0.99", "How fast the spring pull-back fades. Lower = quicker kill of oscillation when the wheel returns to centre. 0.65 default; 0.1–0.4 on strong bases."),
                    Hsl("Output Smoothing", "0.05 – 1", "Smooths the force output. 0.35 = smooth but responsive; 1.0 = no smoothing. Reduces the notchy feel from the game's discrete steering steps.")),
                S("Crash Impact",
                    P("Detects wall and car collisions from G-force spikes and delivers a directional kick. Per-wheel games only, and safety-clamped by default."),
                    B("Enable Crash Forces — master switch for the whole section."),
                    Hsl("Impact Gain", "0 – 1", "How strong the crash kick feels. 0.3 = subtle nudge, 0.6 = noticeable kick, 1.0 = full force."),
                    Hsl("Safety Clamp", "0.1 – 1.0", "Maximum crash force as a fraction of total output. Prevents wall impacts from generating dangerous torque. 50% default is safe for all wheels."),
                    Hsl("Trigger Threshold (G)", "1 – 10 G", "The G-force spike that counts as a crash. 3G = typical racing collision, 5G = heavy impact, 8G+ = extreme. Higher = fewer false triggers."),
                    Hsl("Decay Rate", "0.5 – 0.98", "How fast the impact force fades. 0.88 = quick punch (~100 ms), 0.95 = longer shake (~250 ms), 0.98 = sustained rumble."),
                    Hsl("Min Speed (km/h)", "0 – 50", "Below this speed no crash forces are generated — prevents false triggers in the pit lane."),
                    Note("Hazard: removing the safety clamp", "Disabling the safety clamp allows crash forces up to 100% of wheel output. Sudden powerful torque spikes can cause injury or damage. Only disable if you understand the risk and want maximum realism.")),
                S("Tyre Condition",
                    P("Simulates tyre failure: blowouts, pressure loss, and damage asymmetry. Per-wheel games only."),
                    B("Enable Tyre Condition Effects — master switch for the section."),
                    Hsl("Blowout Vibration", "0 – 1", "The violent shake when a tyre bursts, strongest at the affected corner. 0.40 = default, 0.60 = strong."),
                    Hsl("Pressure Loss Rumble", "0 – 1", "A subtle low rumble as pressure drops below threshold, building as it falls further. Feels like a slowly dying tyre."),
                    Hsl("Damage Asymmetry", "0 – 1", "A constant steering pull toward the more damaged side when tyre damage is uneven across an axle. Higher = stronger pull."),
                    Hsl("Blowout Pressure Threshold", "0 – 1", "The pressure fraction (of normal) below which a blowout can happen. 0.40 = blowout at 40% pressure; lower = tyres deflate further before bursting."),
                    Hsl("Max Blowout Amplitude", "0 – 1", "Peak vibration during a blowout. 0.25 = moderate shake, 0.50 = violent, 1.0 = extreme.")),
                S("Column Force (RaceRoom · Le Mans Ultimate)",
                    P("Column-force games do not expose per-wheel physics, so the wheel is driven directly from the game's steering-column torque. These sliders control that signal."),
                    Hsl("Main Force Gain", "0 – 10", "Scales the total steering-force magnitude. Higher = stronger overall. Start at 1.0 (for a Moza R5)."),
                    Hsl("Force Scale", "0.1 – 5", "Divides the game's steering-force percentage. At 1.0, 100% steering = 1.0 output; lower = stronger. Start at 1.0."),
                    Hsl("Brake Boost", "0 – 1", "Extra centering force under braking, simulating the front grip gained from weight transfer. 0 = off, 0.15 = subtle, higher = stronger brake pull."),
                    Hsl("Brake Boost Threshold", "0 – 1", "How far the brake must be pressed before the boost engages. 0.1 = a light touch is enough; higher = needs harder braking."),
                    Hsl("Tyre Grip Effect", "0 – 2", "How strongly the front tyres' grip reduces the force. At 1.0: full grip = full force, zero grip ≈ 10% force. At 0 the force never fades. Gives the 'losing grip = wheel goes light' feel."),
                    Hsl("Torque LFE Mod", "0 – 2", "Scales the engine rumble by the actual engine torque. 0 = torque has no effect on the rumble; higher = rumble swells with the engine load."),
                    Hsl("Flatspot Vibration", "0 – 2", "A sharp pulse once per wheel revolution when a tyre has a flatspot. Higher = more pronounced thump-thump-thump."),
                    Hsl("Surface Feel", "0 – 2", "Rumble when the tyres leave the racing surface. Gravel reads coarse, grass reads softer. Higher = more surface detail."),
                    Hsl("Brake Pressure Feel", "0 – 2", "Brake-bite texture from per-wheel brake pressure — a subtle vibration under hard braking. Higher = more brake feel through the wheel."),
                    Hsl("TC Feel", "0 – 2", "A subtle force release when traction control cuts power. Higher = you feel each intervention as a small tug of the wheel."),
                    Hsl("Core Smoothing", "0 – 0.5", "Smoothing on the main force. 0 = raw; 0.15 = light, keeps steering feel; 0.5 = heavy, may feel sluggish."),
                    Hsl("Detail Smoothing", "0 – 0.8", "Smoothing on the texture effects. 0 = raw vibrations; 0.3 = moderate (calms jitter, keeps rumble strips); 0.8 = heavy, kills texture."),
                    Hsl("Grip Scale (LMU)", "0 – 1", "Le Mans Ultimate: how much centering force fades as the front tyres approach zero grip, using the game's real per-wheel grip fraction. 0 = always full force; 1 = full fade at zero grip."),
                    Hsl("Tyre Temp Feel (LMU)", "0 – 1", "Le Mans Ultimate: subtle texture from cold (under ~75°C) or overheated (over ~105°C) tyres. 0 = off; higher = more temperature texture.")),
                S("Vibrations",
                    P("All the vibration feedback mixed into the main force: kerbs, slip, road texture, ABS, off-track surfaces. Everything here scales with the Vibration Master."),
                    Hsl("Vibration Master", "0 – 10", "Master volume for all vibration effects — scales Curb, Slip, Road and ABS together. Turn this up first, then balance the individual sources."),
                    Hsl("Curb Gain", "0 – 10", "Kerb and rumble-strip strike intensity. Higher = the sharp rattle over sausage kerbs. Also scales kerb bumps in the main force."),
                    Hsl("Slip", "0 – 10", "Tyre-slip vibration intensity — the buzz when wheels spin or lock. Higher = more of the 'slipping' texture."),
                    Hsl("Road", "0 – 10", "Road-surface vibration intensity. Higher = the constant fine surface texture, like tarmac grain, is stronger."),
                    Hsl("ABS Intensity", "0 – 10", "ABS pulse vibration — and adds pulses to the main steering force when ABS kicks in. Higher = each ABS cycle is felt more clearly."),
                    Hsl("Suspension Road", "0 – 10", "Road texture derived from suspension movement, fed into the main force channel. Higher = more detailed surface feel from the suspension geometry."),
                    Hsl("Offtrack Gain", "0 – 2", "Overall intensity of off-track feedback. 0 = nothing off track, 0.5 = subtle, 1.0 = strong rumble over grass/gravel."),
                    Hsl("Offtrack Severity", "0 – 10", "How aggressively suspension movement is amplified off track. Higher = more violent rumble on grass and gravel."),
                    Hsl("ABS Pulse Strength", "0 – 1", "How punchy each ABS pulse feels. Gentle cars ≈ 0.10, aggressive cars ≈ 0.25–0.50.")),
                S("Damping & Friction",
                    P("Speed-sensitive steering resistance. Per-wheel games and Le Mans Ultimate only."),
                    Hsl("Speed Damping", "0 – 25", "Viscous damping that increases with car speed — the steering tightens as you go faster, like real power steering that firms up. Higher = heavier at speed. Scaled by Damping Speed Ref."),
                    Hsl("Friction", "0 – 20", "Constant resistance whenever you turn the wheel (Coulomb friction). Higher = heavier, more mechanical, 'coggy' feel; too high = numb and sticky."),
                    Hsl("Inertia", "0 – 20", "Simulated steering-column inertia: resists rapid direction changes, increasing with speed. Higher = the wheel feels heavier to flick side to side; helps stability but can dull flick entries."),
                    Hsl("Damping Speed Ref (km/h)", "50 – 500", "The speed at which speed-based damping reaches full strength. Lower = damping kicks in sooner (firm at lower speeds).")),
                S("Dynamic Effects",
                    P("Supplemental forces from G-forces and suspension movement."),
                    Hsl("Cornering Force", "0 – 5", "Force from lateral G-force in corners. Higher = more of the 'the car is leaning on the wheel' sensation in long, fast corners."),
                    Hsl("Road Feel", "0 – 5", "Force from rapid suspension compression changes — bumps and kerbs. Only reacts to changes, so it adds punch without adding constant heaviness."),
                    Hsl("Accel/Braking Force", "0 – 5", "Force from longitudinal G-force. Higher = you feel weight transfer under braking and acceleration as a pull on the wheel."),
                    Hsl("Car Rotation Force", "0 – 5", "Force from how fast the car is rotating (yaw rate). Higher = clearer feel of slides and direction transitions.")),
                S("LFE — Low-Frequency Effects",
                    P("A low-frequency rumble driven by suspension travel and speed — feels like chassis road texture, especially on strong wheelbases."),
                    B("Enable LFE — master switch."),
                    Hsl("LFE Gain", "0 – 1", "Overall intensity of the low-frequency effect in the main force."),
                    Hsl("Frequency", "3 – 30 Hz", "The base rumble frequency. Lower = deeper, heavier thump; higher = faster, buzzier."),
                    Hsl("Suspension Drive", "0 – 1", "How much suspension travel drives the effect envelope. Higher = more reactive to bumps."),
                    Hsl("Speed Scaling", "0 – 1", "How much vehicle speed modulates the frequency. Higher = the rumble speeds up with road speed."),
                    Hsl("RPM Drive", "0 – 1", "How much engine RPM drives intensity and frequency. Higher = more engine-vibration rumble at high revs.")),
                S("Signal Processing",
                    P("How the force behaves around the steering centre, plus smoothing and filtering."),
                    Hsl("Center Suppress (deg)", "0 – 30°", "A zone near centre where forces fade to zero with a quadratic ramp. Wider = a bigger 'quiet zone' around straight-ahead, killing any centre twitch. Only active when Sign Correction is on."),
                    Hsl("Noise Floor", "0 – 0.05", "Forces below this level are silenced. Higher = a still, quiet wheel when nothing is happening — but fine detail is lost too."),
                    Hsl("Center Knee Power", "0.5 – 3", "Shapes how force ramps up from centre. 1.0 = normal; higher = lighter right at centre with a sharper onset as you turn — a 'notchy then firm' feel."),
                    Hsl("Center Blend (deg)", "0 – 10°", "The angle over which lateral (cornering) force is suppressed near centre. Prevents Fy buzz driving straight. Higher = cornering weight comes in later."),
                    Hsl("Center Sharpness (deg)", "0 – 10°", "Column-force games: the angle at which centering force reaches full via a smooth curve. Lower = crisper, more defined on-centre feel; 0 = disabled (crispest)."),
                    B("Mute Gear Change FFB — suppresses force spikes during gear shifts. On by default; leave it on."),
                    Hsl("Steer Vel Reference", "1 – 50", "Reference speed for steering-velocity normalisation. Higher = less damping response to fast steering inputs (the wheel stays freer when you flick it)."),
                    Hsl("Velocity Deadzone", "0 – 0.5", "Minimum steering speed before damping engages. Higher = damping only during fast turns. Great anti-bounce-back control for the centre."),
                    Hsl("Low Speed Smooth (km/h)", "0 – 100", "Below this speed, all channel smoothing increases. Higher = silkier low-speed feel in slow corners, but less detail.")),
                S("Auto-Gain",
                    P("Automatically adjusts overall strength so different cars feel similar — compensates for cars with naturally heavy or light FFB."),
                    B("Enable Auto-Gain — master switch."),
                    Hsl("Auto-Gain Scale", "0.1 – 5", "The target level it compensates toward. Higher = stronger auto-compensation, more similar feel across cars.")),
                S("Wet Weather",
                    P("Adjusts the whole feel for wet tracks: suppresses vibration detail, widens slip curves, raises the noise floor, and can simulate hydroplaning. Enable before driving in rain. Per-wheel games only."),
                    B("Enable Wet Weather — master switch.",
                        "Auto-Detect Wet Conditions — the app reads track wetness from the game. When off, Manual Intensity is used instead."),
                    Hsl("Road Vibration", "0 – 1", "How much road-surface vibration is suppressed in the wet. 0 = full road feel, 0.7 = dampened, 1.0 = road feel removed — like the tyres are on a film of water."),
                    Hsl("Curb Vibration", "0 – 1", "How much kerb vibration is suppressed in the wet. Kerbs feel muted on wet tracks."),
                    Hsl("Tire Scrub", "0 – 1", "How much scrub texture is suppressed. Less grip = less scrub grain in the wet."),
                    Hsl("Manual Intensity", "0 – 1", "When auto-detect is off: the wetness level. 0 = dry, 1 = heavy rain."),
                    Hsl("Peak Slip Angle Mult", "1.0 – 3.0", "Widens the slip curve: 1.0 = dry curve, 1.6 = wider wet curve — peak grip happens at larger slip angles, so the limit feel comes later and softer."),
                    Hsl("Damping Reduction", "0 – 1", "How much speed damping is reduced in the wet. Wet tyres have less mechanical grip = less steering resistance."),
                    Hsl("Noise Floor Boost", "0 – 1", "How much the noise floor is raised in the wet. Masks the fine detail that would be lost on wet tarmac anyway."),
                    B("Enable Hydroplaning Feel — adds force loss at speed on standing water."),
                    Hsl("Speed Threshold (km/h)", "60 – 250", "Speed above which hydroplaning risk builds. Lower = earlier onset; higher = only at very high speed."),
                    Hsl("Max Attenuation", "0 – 0.8", "Maximum force reduction while hydroplaning. 0.3 = subtle lightness, 0.6 = noticeable force loss, 0.8 = severe aquaplaning — the wheel suddenly goes weightless."))
            ),

            A("Equalizer", "Shaping the final force signal by frequency — 10 bands and what they feel like",
                new[] { "equalizer", "eq", "band", "frequency", "hz", "boost", "cut", "texture", "weight", "curve" },
                S("What the equalizer does",
                    P("The equalizer shapes the final force signal right before it reaches the wheel — like an audio EQ, but for force. Each of the 10 vertical sliders covers a frequency range of the force signal. Boosting a band makes that kind of force stronger; cutting it removes it."),
                    P("Start flat (0 dB on every band) and adjust one band at a time while driving. The bands are tuned to the app's own effect frequencies, so each one maps to a recognisable feeling."),
                    Note("Tip", "A flat EQ with good master settings is often the best starting point. Use the EQ for broad 'character' changes (heavy vs light wheel, smooth vs detailed) rather than fixing a single effect — specific effects have their own sliders on the FFB Tuning page.")),
                S("The 10 bands",
                    Hsl("Steer Weight — 2 Hz", "-12 to +12 dB", "The very lowest, heaviest forces: overall steering resistance and parking-lot effort. Boost = a heavier, weightier wheel; cut = a lighter, freer wheel."),
                    Hsl("Weight Transfer — 4 Hz", "-12 to +12 dB", "Body roll, brake dive and acceleration squat. Boost = more sense of the car pitching and leaning under load changes."),
                    Hsl("Self Align — 8 Hz", "-12 to +12 dB", "The self-centering torque: how firmly the wheel returns to centre and how grip balance feels. Boost = stronger, more present centre; cut = a softer, more relaxed centre."),
                    Hsl("Steering Precision — 12 Hz", "-12 to +12 dB", "Small corrections and line tracking. Boost = the wheel feels more 'connected' and precise on minor inputs; too much can feel nervous."),
                    Hsl("Turn-In Response — 18 Hz", "-12 to +12 dB", "Initial bite and direction changes. Boost = a sharper, more eager response when you first turn the wheel into a corner."),
                    Hsl("Road Texture — 25 Hz", "-12 to +12 dB", "Tarmac grain and surface roughness. Boost = more of the constant fine surface detail; cut = a smoother, more 'polished' feel."),
                    Hsl("Bump Detail — 35 Hz", "-12 to +12 dB", "Patches, seams and road features. Boost = each surface imperfection is more distinct as you hit it."),
                    Hsl("Kerb Strike — 50 Hz", "-12 to +12 dB", "Kerb hits, potholes and sharp impacts. Boost = kerb strikes rattle harder and cut through the rest of the force."),
                    Hsl("Wheel Chatter — 70 Hz", "-12 to +12 dB", "Rapid vibration and wheel buzz — often the frequency of 'flutters' on coarse surfaces or under lock-up. Cut this band first if the wheel feels buzzy."),
                    Hsl("ABS/TC Pulses — 100 Hz", "-12 to +12 dB", "The finest vibration: ABS cycling and traction-control pulsing. Boost = assist interventions are clearly felt as rapid micro-pulses.")),
                S("Presets & practical use",
                    B("Use the Enable checkbox to A/B the whole EQ instantly.",
                        "A boost of +3 to +6 dB on Self Align and Steering Precision with a small cut on Wheel Chatter is a common 'crisp centre' starting point.",
                        "If the wheel feels harsh, cut the 50 Hz and 70 Hz bands first — they carry the harshest impacts.",
                        "If the wheel feels dead at low speed, boost the 2 Hz and 4 Hz bands."))
            ),

            A("FFB Coach", "The AI tuning assistant that reads your telemetry and recommends changes",
                new[] { "ffb coach", "ai", "assistant", "chat", "monitor", "snapshot", "analyze", "recommendation", "telemetry analysis" },
                S("What it is",
                    P("FFB Coach is an AI assistant that helps you tune. It reads real telemetry from your driving (or from a saved snapshot) and talks you through what the data shows — oscillation, snapping, clipping, weak centre — and suggests specific slider changes."),
                    P("The FFB Coach needs an AI provider configured first: open Settings → AI Coach and paste your OpenCode Go API key (from opencode.ai/auth). The default model (DeepSeek V4 Flash) is cheap to run.")),
                S("Ways to use it",
                    B("Chat with AI — a conversation where you describe a problem ('the wheel oscillates on straights') and it asks questions, then recommends changes.",
                        "Live Monitor — the coach watches your live telemetry while you drive and comments on what it sees.",
                        "Load Snapshot Data — analyse a saved snapshot (press your assigned snapshot button in-game, then load it here). This is the most reliable mode: the coach analyses real recorded signals."),
                    P("During a session the top bar shows the state (Thinking…, Chat Active, Applying, Summary). Restart clears the conversation; Summary produces a final write-up of recommended changes."),
                    Note("Trust but verify", "The coach's suggestions are applied to your profile and can always be reverted. Change one recommended slider at a time and drive before accepting the next."))
            ),

            A("Devices — LED Effects", "Wheel LED strips: brightness, flash effects, colors and RPM thresholds",
                new[] { "devices", "led", "lights", "rpm", "shift light", "flash", "brightness", "color", "color scheme", "threshold" },
                S("What this tab does",
                    P("The LED Effects tab controls the LED strip on your wheel — the shift lights. Which options are available depends on the wheel: some wheels only accept basic on/off LEDs, others (SDK-connected wheels) allow full RGB control and brightness."),
                    P("A live preview bar at the top shows what the LEDs will look like.")),
                S("Sections and controls",
                    Hsl("Brightness", "5 – 100%", "Overall LED brightness (SDK-connected wheels only). Lower = dimmer so it is less distracting at night."),
                    B("Shift / Limiter Flash — all LEDs flash at the redline or when the rev limiter cuts.",
                        "Pit Limiter Flash — alternating outer LEDs while the pit limiter is active.",
                        "ABS Flash — the first and last LED flash while ABS is working.",
                        "Race Flag Indicators — LEDs show yellow, red and blue race flags."),
                    Hsl("Flash Speed", "2 – 60", "How fast flashing effects blink. Lower = faster (2 is very fast, 60 is slow)."),
                    B("Color Scheme — for per-LED RGB wheels: Traffic Light (green/yellow/red), Blue Gradient, Red Hot, Monochrome, or Custom."),
                    B("RPM Thresholds — presets: Default (50–100%), Early (30–100%), Late (70–100%), Linear (10–100%), or Custom. Each of the 10 LEDs lights up when RPM crosses its own threshold (as a % of redline). Pick a preset, then switch to Custom to fine-tune individual LEDs."))
            ),

            A("Devices — Haptic Pad (HF8)", "The seat/back vibration pad: zone mapping, sources, and gains",
                new[] { "devices", "haptic", "hf8", "pad", "vibration", "seat", "back", "motor", "zone", "kerb", "suspension", "engine" },
                S("What this tab does",
                    P("The Haptic Pad tab controls a Next Level Racing HF8 (or HF8 Pro) seat pad: 8 vibration motors across your seat and lower back. You map telemetry sources — suspension, tyre slip, kerbs, lateral G, engine RPM — to each motor zone, so a kerb strike on the left side buzzes the left side of the seat."),
                    Note("Before it will connect", "Connect the HF8 via USB and close the NLR HFS software — it holds exclusive HID access and blocks this app.")),
                S("Master controls",
                    B("Haptic Output — master enable switch."),
                    Hsl("Master Gain", "0 – 1", "Overall intensity for all motor zones. Turn this up first, then balance zones."),
                    Hsl("Output Rate", "15 – 120 Hz", "The motor update rate: 75 Hz for the HF8 Pro, 15 Hz for the original HF8. Set it to match your hardware or the motors will feel wrong.")),
                S("The 8 zones",
                    P("Zones are laid out as four rows: Seat Front (left/right), Seat Rear (left/right), Back Lower (left/right), Back Upper (left/right). Each zone has:"),
                    Hsl("Zone Intensity", "0 – 1", "How strongly this individual zone vibrates."),
                    Hsl("Suspension", "0 – 3", "How much suspension travel feeds this zone — bumps and kerbs through the seat."),
                    Hsl("Tire Slip", "0 – 3", "How much tyre slip feeds this zone — wheelspin and slides."),
                    Hsl("Kerbs", "0 – 3", "How much kerb-strike vibration feeds this zone."),
                    Hsl("Lateral G", "0 – 3", "How much cornering G-force feeds this zone — you lean into the seat in long corners."),
                    Hsl("Engine RPM", "0 – 3", "How much engine revs feed this zone — a constant buzz that follows the RPM."),
                    B("Enabled — switches the zone on/off.",
                        "Copy from here / Copy → — copy one zone's whole setup to another zone so the left/right sides match."),
                    Note("Suggested start", "Front-left zone = Suspension 1.0 + Kerbs 1.0; front-right zone mirrored. Back zones = Lateral G 1.0. Engine RPM 0.5 across the back for a subtle rev buzz. Then raise Master Gain while driving until it feels right.")),
                S("Testing",
                    P("The Test Motors button opens a popup that fires individual motors so you can verify the pad is wired and seated correctly before driving."))
            ),

            A("Devices — Pedals", "Pedal haptics, physical pedal input, routing and calibration",
                new[] { "devices", "pedals", "pedal", "haptic", "brake", "gas", "clutch", "osoyoo", "arduino", "serial", "calibration", "deadzone", "abs", "tc" },
                S("What this tab does",
                    P("The Pedals tab controls vibration feedback in your pedals. It is built around an Osoyoo Arduino Uno (or compatible serial device) with brake and gas vibration motors, plus everything needed to use physical pedals as an input source.")),
                S("PEDAL HAPTIC DEVICE (connection)",
                    P("Pick the COM port your Arduino is on (Refresh lists the ports) and press Connect. The motor test panel lets you fire the brake and gas motors at an intensity (0–255) to confirm the wiring before driving — the telemetry feed is paused during tests.")),
                S("Physical Pedal Input",
                    P("When enabled, pedal values come from your physical pedal hardware instead of game telemetry. Keyboard simulation (W = gas, S = brake, A = clutch) is also available for testing. The LIVE PEDAL STATE panel shows which source is active and the live gas/brake/clutch positions.")),
                S("Haptic Output Routing",
                    P("Each effect routes through a pedal column, then that column's master gain scales the whole channel (0–2×)."),
                    Hsl("Brake — Master Gain", "0 – 2", "Overall volume of everything on the brake pedal."),
                    Hsl("Brake — ABS Pulse", "0 – 2", "How strongly the ABS pulsing is felt in the brake pedal — a rapid stutter under hard braking as ABS cycles."),
                    Hsl("Brake — Brake Pressure Hum", "0 – 2", "A constant hum proportional to brake pressure — you feel the brake 'load up' under your foot."),
                    Hsl("Brake — Road Texture", "0 – 2", "Road surface vibration through the brake pedal — tarmac grain and bumps under your foot."),
                    Hsl("Gas — Master Gain", "0 – 2", "Overall volume of everything on the gas pedal."),
                    Hsl("Gas — TC Ignition Cut", "0 – 2", "A pulse in the gas pedal when traction control cuts ignition — you feel the car fighting for grip."),
                    Hsl("Gas — Corner Scrub", "0 – 2", "Front tyre scrub sensation through the gas pedal when cornering hard."),
                    Hsl("Gas — Throttle Position", "0 – 2", "A constant buzz proportional to throttle position."),
                    Hsl("Gas — Engine RPM Buzz", "0 – 2", "Engine vibration buzz that follows the RPM, through the gas pedal."),
                    Hsl("Gas — Curb (Shared)", "0 – 2", "Kerb-strike vibration shared to the gas pedal — kerbs are felt under your foot too."),
                    Hsl("Clutch — Master Gain", "0 – 2", "Overall volume for the clutch column. Note: the current Osoyoo firmware drives brake + gas motors only, so the clutch channel is ready but needs a clutch-capable motor.")),
                S("Calibration",
                    P("Each pedal (gas, brake, clutch) has the same tuning set. Calibrate with the pedal at rest and fully pressed:"),
                    Hsl("Deadzone", "0 – 0.3", "How far the pedal must travel before it registers any input. Removes resting jitter from worn pots."),
                    Hsl("Min Range", "0 – 1", "The raw value that maps to 'pedal fully released'. Set from the resting position."),
                    Hsl("Max Range", "0 – 1", "The raw value that maps to 'pedal fully pressed'. Set from the full-press position."),
                    B("Invert — flips the direction if the pedal reads backwards.",
                        "Smoothing α — how much the signal is smoothed. Higher = smoother but laggier; too high and fast dabs feel mushy."),
                    P("Press Save Pedal Configuration to keep the calibration permanently."))
            ),

            A("Devices — Buttons", "Assigning wheel buttons for snapshots and panic stop",
                new[] { "devices", "buttons", "assign", "snapshot", "panic", "button box", "wheel button" },
                S("What this tab does",
                    P("Assigns physical buttons for two in-app actions.")),
                S("Snapshot button",
                    B("Press your chosen button while driving to auto-save a telemetry snapshot (a recording of the last seconds of force and telemetry data, saved to the snapshots folder for analysis).",
                        "Pick a button that is easy to reach mid-corner — you will be pressing it during interesting moments.")),
                S("Panic stop button",
                    B("Assign a button on a SEPARATE device (ideally a button box) as a hardware panic stop. Pressing it instantly zeroes all FFB output — an emergency brake for the wheel.",
                        "The panic device opens in non-exclusive mode, so it does not conflict with the game or your FFB wheel.",
                        "A hardware panic button is the safest possible setup — even if the app's window loses focus, the button still works."))
            ),

            A("Profiles", "Saving, organising and auto-loading your setups per car and track",
                new[] { "profiles", "profile", "save", "import", "export", "car match", "track match", "auto load", "browser", "json" },
                S("What this page does",
                    P("A profile is a complete snapshot of every slider setting, stored as a JSON file. This page manages them: creating, renaming, deleting, importing, exporting, and — most usefully — telling the app which profile belongs to which car or track.")),
                S("Current Profile & Detection",
                    B("Active Profile — the profile currently in use. Switch with the dropdown.",
                        "Car Match — the car model that auto-loads this profile when detected in-game. Use Detected fills it from the car you are currently driving.",
                        "Track Match — an optional track name for organising profiles by track.",
                        "Detected Car / Detected Track — what the app currently sees in your session.",
                        "Auto-load profile when car changes — the master switch for per-car auto-loading. Switching cars in-game then loads the matching profile automatically.")),
                S("Actions",
                    B("Save Current Profile — writes current settings into the active profile (becomes Save As when a built-in profile is selected, because built-ins cannot be overwritten).",
                        "Save As New Profile… — copies the current settings into a new named profile.",
                        "Rename Profile / Delete Profile — manage your own profiles. Built-in profiles cannot be renamed or deleted.")),
                S("Import / Export",
                    B("Export Profile — saves the active profile as a JSON file you can share or back up.",
                        "Import Profile — loads a profile JSON file and adds it to your collection.")),
                S("Profile Browser (right side)",
                    P("Browse all profiles with search, view modes (flat list, grouped by track, grouped by car), and game filter pills (All Games, AC EVO, RaceRoom, Assetto Corsa, Le Mans Ultimate). Click any profile to activate it instantly."),
                    Note("Built-in profiles", "Profiles marked BUILT-IN are the app's starting points for your car. Save As to create your own editable copy based on them. Profiles with an older format show a version badge — enable Auto Upgrade Profiles in Settings to convert them automatically."))
            ),

            A("Telemetry Profiler", "Live signal analysis: the chart, channels, and snapshot tools",
                new[] { "telemetry", "profiler", "chart", "graph", "snapshot", "export csv", "export analysis", "clipping", "force out", "raw ff" },
                S("What this page does",
                    P("A live, scrolling chart of the FFB pipeline signals — the same data the app uses to build the force. This is the window into what the wheel is being told to do, second by second. It is invaluable when diagnosing problems: oscillation shows up as a sawtooth wave, clipping as flat-topped spikes, weak centre as tiny signal near the middle.")),
                S("Toolbar & readouts",
                    B("Pop Out Overlay — opens the chart in a floating window you can position over the game.",
                        "Snapshot — saves the current telemetry window (CSV + analysis text + animated HTML replay) to the snapshots folder.",
                        "Export Analysis / Export CSV — save the visible data for deeper analysis or sharing.",
                        "Clear — resets the chart.",
                        "Live readouts: Speed, Force Out, Throttle, Brake, Clipping %, Min/Max force, Avg force, Steering angle, Raw FF, peak Mz/Fx/Fy, and the time window."),
                    P("The channel checkboxes (Output, Raw FF, Compress, Gain Out, Post Damp, Dynamic, Speed, Steer°, Throttle, Brake) toggle which signals are drawn, and the legend on the left identifies their colours.")),
                S("Reading the chart",
                    B("Output (orange) — the final force actually sent to the wheel.",
                        "Raw FF (green) — the game's raw force input.",
                        "Compress (cyan) — after compression/limiting stages.",
                        "Gain Out / Post Damp (magenta / orange-red) — later pipeline stages, useful when checking damping behaviour.",
                        "CLIP indicator — when the force hits the wheel's limit, shown as a red CLIP badge and flat-topped signal. Occasional clipping in heavy moments is normal; constant clipping means Output Gain is too high."),
                    P("The bottom strip shows the three most important physics channels live: MzFront, FxFront, FyFront, so you can watch the raw tyre forces while you drive."),
                    Note("Snapshot workflow", "When something feels wrong, press your snapshot button during the moment, then load the snapshot in FFB Coach or export the CSV to see exactly what the pipeline was doing. This is the recommended way to report bugs."))
            ),

            A("Track Map", "Recording track layouts, force heatmaps, and FFB diagnostics",
                new[] { "track map", "track", "map", "record", "lap", "heatmap", "diagnostics", "satellite", "waypoint", "corner", "recommendations" },
                S("What this page does",
                    P("Builds a map of the track as you drive, overlays your car position, records a force heatmap (where the wheel is working hardest), and runs an FFB diagnostics pass that flags suspicious force behaviour at each point on track.")),
                S("Recording a track",
                    B("Press Record Lap and drive a full lap (start/finish in the normal place). The app samples position and force at waypoints.",
                        "Stop, then Complete & Save to finalise. The map is remembered for that track (per game) and auto-detected next time you drive it.",
                        "Export / Import — share a recorded track profile (with heatmap) as a file.",
                        "Calibrate — aligns the recorded map to the track's GPS/satellite data. Live Mode — switches to the live satellite view."),
                    P("The status strip shows corner number, sector, corner count, laps, pit status, track progress, distance from centre, and on/off-track state.")),
                S("Map overlays",
                    B("Heatmap — colours the track line by force output; you can see exactly where the wheel is under the most load.",
                        "Edges — shows the recorded track edges.",
                        "Diagnostics — the FFB health pass: green dots = expected behaviour, yellow = notable event, red = suspicious (possible code/signal issue).",
                        "Satellite — real satellite imagery of the track (needs calibration and internet).")),
                S("FFB Diagnostics panel & Recommendations",
                    P("The left panel explains the dot colours and the verdict. When diagnostics are on, a Recommendations bar appears at the bottom with suggested profile changes — Apply Profile Changes applies them to your profile so you can A/B test immediately."),
                    Note("What 'suspicious' looks like", "Force snapping on a straight, oscillation with no steering input, or force pushing in the same direction as the wheel are classic red flags. Most dots green and at corners = normal driving."))
            ),

            A("Live Map", "OSM track data and satellite view of where you are on track",
                new[] { "live map", "map", "satellite", "osm", "openstreetmap", "gps", "position", "corner" },
                S("What this page does",
                    P("An experimental live map page that shows your position on an OpenStreetMap/satellite view of the track, with live speed, sector, corner, lap, position and pit state readouts."),
                    P("The OSM status bar shows data loading state; Refresh Data reloads the track data. Data quality depends on the track being present in OpenStreetMap — some tracks are incomplete."),
                    Note("Work in progress", "This page is marked WIP in the sidebar — expect rough edges. The Track Map page is the full-featured recording and diagnostics tool."))
            ),

            A("Overlays (OBS)", "Browser-source overlays for streaming and monitoring",
                new[] { "overlays", "obs", "stream", "browser source", "dashboard", "clipping indicator", "overlay", "url", "network" },
                S("What this page does",
                    P("This page provides ready-made browser-source overlays for OBS: live telemetry dashboards you can put on your stream or second monitor. Each overlay is a URL served by the app itself; you add a Browser Source in OBS pointing at that URL.")),
                S("The overlays",
                    B("FFB Telemetry Dashboard — the full dashboard: force output, Mz/Fx/Fy channels, raw tyre data, LUT curve, damping and pipeline stages, speed, steer angle, and clipping indicator. Themes: dark, transparent, compact, clipping. Options: ?theme=dark&charts=all&stats=all.",
                        "OBS Streamer Overlay — a clean, streamer-friendly view: speed, gear, RPM bar, force Nm, clipping, Mz/Fx/Fy, lap counter, track position map and a scrolling force waveform. Transparent background supported (use ?opacity=0.8 to reduce transparency).",
                        "Custom Overlay Builder — tick the modules you want (speed/flags, force & channels, waveform, track map, pedals & steering, tyre heat, G-force meter) and the URL updates automatically. Modules are also usable directly in the URL: ?mods=speed,pedals,tires,gforce.",
                        "Clipping Indicator — a minimal CLIPPING/OK indicator only. Ideal as a thin overlay to warn your viewers when FFB is clipping."),
                    P("Each card has a Copy button for the URL and a Source dropdown (the overlay can serve a different game's data).")),
                S("OBS setup",
                    B("1. Add a new Browser Source to your scene.",
                        "2. Paste the overlay URL.",
                        "3. Set the size to 1920 × 1080 (or match your canvas).",
                        "4. Enable 'Refresh browser when scene becomes active' so the overlay reconnects.",
                        "5. For transparent overlays add ?theme=transparent to the URL.")),
                S("Network access",
                    P("Overlays on the same PC work immediately. For other devices (e.g. a second PC running OBS), press Enable Network Access to open the URL access control list and the Windows firewall for the app's local HTTP server."))
            ),

            A("Settings", "App options, splash screen, themes, voice, AI coach, and debug tools",
                new[] { "settings", "options", "theme", "voice", "ai coach", "api key", "startup", "splash", "start minimised", "auto connect", "tooltips", "debug", "system log", "calibration", "testing guide" },
                S("App Options",
                    B("Start Minimised — launch into the taskbar instead of showing the window.",
                        "Auto Connect — connect to the last used FFB device automatically on startup.",
                        "Auto Start — begin telemetry processing automatically after the device connects (needs Auto Connect).",
                        "Show Tooltips — hover hints everywhere in the app.",
                        "Auto Upgrade Profiles — automatically convert old-format profiles when the app updates. When off, profiles needing an upgrade show a warning badge in the browser.",
                        "Default Start Page — which page the app opens to.")),
                S("Startup Effect",
                    P("Customise the splash screen: show/hide it, and set the startup sound. You can record a sound from your audio output device (start recording, play the game engine sound you want, stop) or Browse for an audio file. Preview plays it back; Clear returns to the default engine sound.")),
                S("Theme",
                    P("Pick the app colour scheme from 10 themes (Onyx, Slate, Obsidian, Graphite, Amber, Crimson, Jade, Cobalt, Rose, Charcoal). Changes apply immediately.")),
                S("Voice",
                    B("Enable voice announcements — the app speaks key events (e.g. profile loaded, session start).",
                        "Engine — the speech engine in use.",
                        "Voice Pack — pre-generated announcement audio cache; Open Voice Pack Folder shows the files.",
                        "Voice (SAPI) — choose the Windows voice. For higher quality, install Windows Natural Voices.",
                        "Volume — announcement loudness.")),
                S("AI Coach",
                    P("Powers the FFB Coach page. Paste your OpenCode Go API key from opencode.ai/auth and pick a model. DeepSeek V4 Flash is the cheapest (~31K analyses per $5); Kimi K2.7 Code and GLM-5.2 give the best analysis quality. Advanced: Custom API Endpoint allows a proxy or different provider (default https://opencode.ai/zen/go/v1).")),
                S("System Log & Debug Tools (right side)",
                    B("System Log — the app's event log; click an entry to select it.",
                        "Copy All — copies the raw debug telemetry snapshot to the clipboard for sharing.",
                        "Testing Guide — opens the FFB testing guide overlay (an in-game cheat sheet of test procedures).",
                        "Calibration — opens the wheel calibration wizard (steering lock, centre, force direction).",
                        "Debug Snapshot — the latest raw telemetry values from shared memory and the pipeline, useful when reporting issues."),
                    Note("Sending a report", "The fastest way to get help: reproduce the problem, then press Send to Dev in the top bar. The pack includes profiles, logs, snapshots and track maps automatically."))
            ),

            A("Troubleshooting & Safety", "Common problems and how to fix them — plus staying safe",
                new[] { "troubleshooting", "problem", "fix", "safety", "panic", "weak", "strong", "oscillation", "oscillate", "snap", "clipping", "no force", "no device", "diagnostic" },
                S("No force at all",
                    B("Is the app RUNNING? Press START in the top bar.",
                        "Is the wheel selected in the Device pill and connected?",
                        "Is the game actually running and in focus (on track, not in a menu)?",
                        "Is the game's own FFB off? If the game is fighting for the wheel, the app's force can be overridden. Set the game FFB to 0 and restart it.",
                        "Is the app window in the foreground? The app pauses forces when another window has focus for a second, so the wheel never fights the game.")),
                S("Force is too weak or too strong",
                    B("Use Output Gain (FFB Tuning → Master Output) as the master volume — that is the control designed for this.",
                        "Then check Sensitivity: lower = stronger (it is inverted).",
                        "Check Max Force Limit — a low limit rounds off the peaks before they reach you.",
                        "In per-wheel games, if Mz feel is weak even maxed out, lower the Mz Scale — it divides the raw signal.")),
                S("The wheel oscillates, snaps or bounces back",
                    B("Watch the Telemetry Profiler while it happens — oscillation shows as a fast sawtooth on the Output line.",
                        "Lower Max Slew Rate — limits how fast force can change.",
                        "Raise Velocity Deadzone (Signal Processing) — stops damping from reacting to tiny centre movements, the classic bounce-back cure.",
                        "Check Center Suppress is on (Sign Correction) and raise Center Suppress degrees if it twitches at centre.",
                        "Lower or disable Wet Weather settings if enabled in the dry.",
                        "If it only happens on straights at speed, reduce Speed Damping or raise Damping Speed Ref.",
                        "If it only happens with kerbs, lower Curb Gain and the 50 Hz EQ band.")),
                S("The wheel feels dead or numb",
                    B("Boost the Self Align (8 Hz) and Steering Precision (12 Hz) EQ bands.",
                        "Check Tyre Forces: Mz is the backbone — raise its gain or lower its Scale.",
                        "Reduce heavy damping: Friction and Speed Damping both dull detail.",
                        "Check the noise floor is not set so high it swallows small forces.")),
                S("Everything was fine, then changed",
                    B("Did the car change? The app may have auto-loaded a different profile (check the Profile pill).",
                        "Did the game change? Different games use different pipelines and show different sliders.",
                        "Check the system log (bottom bar / Settings → System Log) for what happened and when.")),
                S("Safety",
                    B("PANIC — the top bar button zeroes all force instantly. It works from any page.",
                        "A hardware panic button (Devices → Buttons) is the safest option; assign it to a separate button box.",
                        "Keep the Crash Safety Clamp enabled (FFB Tuning → Crash Impact) unless you deliberately want unclamped crash forces.",
                        "Never run other FFB apps alongside this one — forces conflict and the wheel can behave erratically.",
                        "If you are unsure about a strange behaviour, stop the app, press PANIC, and send a diagnostic pack (Send to Dev) before continuing.")),
                S("Still stuck?",
                    P("Press Send to Dev in the top bar after reproducing the problem — the pack includes your profiles, logs, snapshots, track maps and recordings manifest, which is everything needed to diagnose the issue. Check the Chat button for replies."))
            ),
        };
        return articles;
    }
}
