/* FakeWheel RS50 3-device mshidkmdf — each device single collection, CollectionKind registry */
#include "fake_rs50hidkm.h"
UCHAR G_ShortReportDescriptor[] = { 0x06,0x43,0xFF, 0x0A,0x01,0x07, 0xA1,0x01, 0x85,0x10, 0x09,0x01, 0x15,0x00, 0x26,0xFF,0x00, 0x75,0x08, 0x95,0x06, 0x81,0x00, 0x95,0x06, 0x91,0x00, 0xC0, };
UCHAR G_LongReportDescriptor[] = { 0x06,0x43,0xFF, 0x0A,0x02,0x07, 0xA1,0x01, 0x85,0x11, 0x09,0x01, 0x15,0x00, 0x26,0xFF,0x00, 0x75,0x08, 0x95,0x13, 0x81,0x00, 0x95,0x13, 0x91,0x00, 0xC0, };
UCHAR G_VeryLongReportDescriptor[] = { 0x06,0x43,0xFF, 0x0A,0x04,0x07, 0xA1,0x01, 0x85,0x12, 0x09,0x01, 0x15,0x00, 0x26,0xFF,0x00, 0x75,0x08, 0x95,0x3F, 0x81,0x00, 0x95,0x3F, 0x91,0x00, 0xC0, };
HID_DESCRIPTOR G_ShortHidDescriptor = { 0x09, 0x21, 0x0111, 0x00, 0x01, { 0x22, sizeof(G_ShortReportDescriptor) } };
HID_DESCRIPTOR G_LongHidDescriptor = { 0x09, 0x21, 0x0111, 0x00, 0x01, { 0x22, sizeof(G_LongReportDescriptor) } };
HID_DESCRIPTOR G_VeryLongHidDescriptor = { 0x09, 0x21, 0x0111, 0x00, 0x01, { 0x22, sizeof(G_VeryLongReportDescriptor) } };
VOID LogOpen(_In_ PDEVICE_CONTEXT Ctx){ UNREFERENCED_PARAMETER(Ctx); }
VOID LogRaw(_In_ PDEVICE_CONTEXT Ctx,_In_ CHAR D,_In_ const UCHAR* B,_In_ USHORT L){ UNREFERENCED_PARAMETER(Ctx); UNREFERENCED_PARAMETER(D); UNREFERENCED_PARAMETER(B); UNREFERENCED_PARAMETER(L); }
ULONGLONG TickMs(VOID){ return 0; }
NTSTATUS RequestCopyFromBuffer(_In_ WDFREQUEST R,_In_ PVOID S,_In_ size_t N){ PVOID b; size_t l; NTSTATUS s=WdfRequestRetrieveOutputBuffer(R,N,&b,&l); if(!NT_SUCCESS(s)) return s; RtlCopyMemory(b,S,N); WdfRequestSetInformation(R,N); return STATUS_SUCCESS; }
NTSTATUS RequestGetHidXferPacket_ToReadFromDevice(_In_ WDFREQUEST R,_Out_ HID_XFER_PACKET* P){ WDF_REQUEST_PARAMETERS pr; WDF_REQUEST_PARAMETERS_INIT(&pr); WdfRequestGetParameters(R,&pr); if(pr.Parameters.DeviceIoControl.OutputBufferLength<sizeof(HID_XFER_PACKET)) return STATUS_BUFFER_TOO_SMALL; RtlCopyMemory(P,WdfRequestWdmGetIrp(R)->UserBuffer,sizeof(HID_XFER_PACKET)); return STATUS_SUCCESS; }
NTSTATUS RequestGetHidXferPacket_ToWriteToDevice(_In_ WDFREQUEST R,_Out_ HID_XFER_PACKET* P){ WDF_REQUEST_PARAMETERS pr; WDF_REQUEST_PARAMETERS_INIT(&pr); WdfRequestGetParameters(R,&pr); if(pr.Parameters.DeviceIoControl.InputBufferLength<sizeof(HID_XFER_PACKET)) return STATUS_BUFFER_TOO_SMALL; RtlCopyMemory(P,WdfRequestWdmGetIrp(R)->UserBuffer,sizeof(HID_XFER_PACKET)); return STATUS_SUCCESS; }
NTSTATUS ReadReport(_In_ PQUEUE_CONTEXT QC,_In_ WDFREQUEST R,_Out_ BOOLEAN* CR){ PDEVICE_CONTEXT dc=QC->DeviceContext; UCHAR e[64]={0}; e[0]=0x10; NTSTATUS s=RequestCopyFromBuffer(R,e,dc->HidDescriptor.DescriptorList[0].wReportLength>64?64:dc->HidDescriptor.DescriptorList[0].wReportLength); *CR=TRUE; UNREFERENCED_PARAMETER(dc); return s; }
NTSTATUS WriteReport(_In_ PQUEUE_CONTEXT QC,_In_ WDFREQUEST R){ UNREFERENCED_PARAMETER(QC); WdfRequestComplete(R,STATUS_SUCCESS); return STATUS_SUCCESS; }
NTSTATUS GetFeature(_In_ PQUEUE_CONTEXT QC,_In_ WDFREQUEST R){ UCHAR f[64]={0x10,0xFF,0,0,0,0,0}; return RequestCopyFromBuffer(R,f,7); UNREFERENCED_PARAMETER(QC); }
NTSTATUS SetFeature(_In_ PQUEUE_CONTEXT QC,_In_ WDFREQUEST R){ UNREFERENCED_PARAMETER(QC); WdfRequestComplete(R,STATUS_SUCCESS); return STATUS_SUCCESS; }
NTSTATUS GetInputReport(_In_ PQUEUE_CONTEXT QC,_In_ WDFREQUEST R){ BOOLEAN b; return ReadReport(QC,R,&b); }
NTSTATUS SetOutputReport(_In_ PQUEUE_CONTEXT QC,_In_ WDFREQUEST R){ return WriteReport(QC,R); }
NTSTATUS QueueCreate(_In_ WDFDEVICE D,_Out_ WDFQUEUE* Q){ WDF_IO_QUEUE_CONFIG c; WDF_OBJECT_ATTRIBUTES a; WDFQUEUE q; WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&c,WdfIoQueueDispatchParallel); c.EvtIoInternalDeviceControl=EvtIoDeviceControl; WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&a,QUEUE_CONTEXT); NTSTATUS s=WdfIoQueueCreate(D,&c,&a,&q); if(!NT_SUCCESS(s)) return s; PQUEUE_CONTEXT qc=GetQueueContext(q); qc->Queue=q; qc->DeviceContext=GetDeviceContext(D); *Q=q; return STATUS_SUCCESS; }
NTSTATUS ManualQueueCreate(_In_ WDFDEVICE D,_Out_ WDFQUEUE* Q){ WDF_IO_QUEUE_CONFIG c; WDF_OBJECT_ATTRIBUTES a; WDFQUEUE q; WDF_IO_QUEUE_CONFIG_INIT(&c,WdfIoQueueDispatchManual); c.EvtIoInternalDeviceControl=EvtIoDeviceControl; WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&a,MANUAL_QUEUE_CONTEXT); NTSTATUS s=WdfIoQueueCreate(D,&c,&a,&q); if(!NT_SUCCESS(s)) return s; PMANUAL_QUEUE_CONTEXT qc=GetManualQueueContext(q); qc->Queue=q; qc->DeviceContext=GetDeviceContext(D); *Q=q; return STATUS_SUCCESS; }
VOID EvtIoDeviceControl(_In_ WDFQUEUE Q,_In_ WDFREQUEST R,_In_ size_t O,_In_ size_t I,_In_ ULONG C){ PDEVICE_CONTEXT dc=GetDeviceContext(WdfIoQueueGetDevice(Q)); PQUEUE_CONTEXT qc=GetQueueContext(Q); NTSTATUS s; BOOLEAN cr=TRUE; UNREFERENCED_PARAMETER(O); UNREFERENCED_PARAMETER(I); switch(C){ case IOCTL_HID_GET_DEVICE_DESCRIPTOR: s=RequestCopyFromBuffer(R,&dc->HidDescriptor,dc->HidDescriptor.bLength); break; case IOCTL_HID_GET_DEVICE_ATTRIBUTES: s=RequestCopyFromBuffer(R,&dc->HidDeviceAttributes,sizeof(HID_DEVICE_ATTRIBUTES)); break; case IOCTL_HID_GET_REPORT_DESCRIPTOR: s=RequestCopyFromBuffer(R,dc->ReportDescriptor,dc->HidDescriptor.DescriptorList[0].wReportLength); break; case IOCTL_HID_GET_COLLECTION_INFORMATION: { HID_COLLECTION_INFORMATION ci; RtlZeroMemory(&ci,sizeof(ci)); ci.DescriptorSize=dc->HidDescriptor.DescriptorList[0].wReportLength; ci.Polled=FALSE; ci.VendorID=dc->HidDeviceAttributes.VendorID; ci.ProductID=dc->HidDeviceAttributes.ProductID; ci.VersionNumber=dc->HidDeviceAttributes.VersionNumber; s=RequestCopyFromBuffer(R,&ci,sizeof(ci)); break; } case IOCTL_HID_GET_COLLECTION_DESCRIPTOR: s=RequestCopyFromBuffer(R,dc->ReportDescriptor,dc->HidDescriptor.DescriptorList[0].wReportLength); break; case IOCTL_HID_READ_REPORT: s=ReadReport(qc,R,&cr); break; case IOCTL_HID_WRITE_REPORT: s=WriteReport(qc,R); cr=FALSE; break; case IOCTL_HID_GET_FEATURE: s=GetFeature(qc,R); break; case IOCTL_HID_SET_FEATURE: s=SetFeature(qc,R); cr=FALSE; break; case IOCTL_HID_GET_INPUT_REPORT: s=GetInputReport(qc,R); break; case IOCTL_HID_SET_OUTPUT_REPORT: s=SetOutputReport(qc,R); cr=FALSE; break; default: s=STATUS_SUCCESS; break; } if(cr) WdfRequestComplete(R,s); }
NTSTATUS DriverEntry(_In_ PDRIVER_OBJECT d,_In_ PUNICODE_STRING r){ WDF_DRIVER_CONFIG c; WDF_DRIVER_CONFIG_INIT(&c,EvtDeviceAdd); c.EvtDriverUnload=EvtDriverContextCleanup; return WdfDriverCreate(d,r,WDF_NO_OBJECT_ATTRIBUTES,&c,WDF_NO_HANDLE); }
VOID EvtDriverContextCleanup(_In_ WDFOBJECT o){ UNREFERENCED_PARAMETER(o); }
NTSTATUS EvtDeviceAdd(_In_ WDFDRIVER drv,_Inout_ PWDFDEVICE_INIT init){ UNREFERENCED_PARAMETER(drv); WdfFdoInitSetFilter(init); WDFDEVICE dev; PDEVICE_CONTEXT ctx; WDF_OBJECT_ATTRIBUTES a; NTSTATUS s; WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&a,DEVICE_CONTEXT); s=WdfDeviceCreate(&init,&a,&dev); if(!NT_SUCCESS(s)) return s; ctx=GetDeviceContext(dev); ctx->Device=dev; RtlZeroMemory(&ctx->HidDeviceAttributes,sizeof(HID_DEVICE_ATTRIBUTES)); ctx->HidDeviceAttributes.Size=sizeof(HID_DEVICE_ATTRIBUTES); ctx->HidDeviceAttributes.VendorID=0x046D; ctx->HidDeviceAttributes.ProductID=0xC276; ctx->HidDeviceAttributes.VersionNumber=0x0100; WDFKEY hk; UNICODE_STRING n; RtlInitUnicodeString(&n,L"CollectionKind"); if(NT_SUCCESS(WdfDeviceOpenRegistryKey(dev,PLUGPLAY_REGKEY_DEVICE,KEY_READ,WDF_NO_OBJECT_ATTRIBUTES,&hk))){ ULONG v; if(NT_SUCCESS(WdfRegistryQueryULong(hk,&n,&v))){ if(v==0){ ctx->ReportDescriptor=G_ShortReportDescriptor; ctx->HidDescriptor=G_ShortHidDescriptor; } else if(v==1){ ctx->ReportDescriptor=G_LongReportDescriptor; ctx->HidDescriptor=G_LongHidDescriptor; } else { ctx->ReportDescriptor=G_VeryLongReportDescriptor; ctx->HidDescriptor=G_VeryLongHidDescriptor; } WdfRegistryClose(hk); } else { ctx->ReportDescriptor=G_ShortReportDescriptor; ctx->HidDescriptor=G_ShortHidDescriptor; } } else { ctx->ReportDescriptor=G_ShortReportDescriptor; ctx->HidDescriptor=G_ShortHidDescriptor; } s=QueueCreate(dev,&ctx->DefaultQueue); if(!NT_SUCCESS(s)) return s; s=ManualQueueCreate(dev,&ctx->ManualQueue); if(!NT_SUCCESS(s)) return s; return STATUS_SUCCESS; }
